language: node_js
sudo: false
node_js:
  - 0.1
  - 4
  - node
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
  - npm install coveralls
  - 'npm run coverage | coveralls'
